apps/vrok_web/lib/vrok_web/router.ex
defmodule VrokWeb.Router do
  use VrokWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(Vrok.Auth, repo: Vrok.Repo)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", VrokWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/viewer", ViewerController, :index)
    resources("/users", UserController, only: [:index, :show, :new, :create])
    resources("/sessions", SessionController, only: [:new, :create, :delete])

    resources "/operations", OperationController, only: [:index, :new, :create, :delete] do
      resources("/scenes", SceneController, only: [:index, :show])
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", VrokWeb do
  #   pipe_through :api
  # end
end

apps/vrok_web/lib/vrok/operation_repo/filter.ex
defmodule Vrok.OperationRepo.Filter do
  import String, only: [downcase: 1]
  def run(operations, query \\ "") when is_binary(query) do

    Enum.filter(operations, fn (operation) -> contains_query(operation, query) end)
  end

  defp contains_query(operation, ""), do: false

  defp contains_query(operation, query) do
    query = String.downcase(query)
    with  result <- String.downcase(operation.title) =~ query,
          result <- [result, String.downcase(operation.description) =~ query],
          result <- [result, tags_contain(operation.tags, query)]
    do
      result
      |> IO.inspect
      |> List.flatten([])
      |> Enum.member?(true)
    end
  end

  def tags_contain(tags, query) do
    tags
    |> Enum.map(fn (tag) -> downcase(tag) =~ query end)
    |> Enum.member?(true)
  end

end

apps/vrok_web/lib/vrok/scene_repo/filter.ex
defmodule Vrok.SceneRepo.Filter do
  import String, only: [downcase: 1]
  def run(scenes, query \\ "") when is_binary(query) do

    Enum.filter(scenes, fn (scene) -> contains_query(scene, query) end)
  end

  defp contains_query(scene, ""), do: false

  defp contains_query(scene, query) do
    query = String.downcase(query)
    with  result <- String.downcase(scene.title) =~ query,
          result <- [result, String.downcase(scene.description) =~ query],
          result <- [result, tags_contain(scene.tags, query)]
    do
      result
      |> List.flatten([])
      |> Enum.member?(true)
    end
  end

  def tags_contain(tags, query) do
    tags
    |> Enum.map(fn (tag) -> downcase(tag) =~ query end)
    |> Enum.member?(true)
  end

end

apps/vrok_web/lib/vrok_web/controllers/operation_controller.ex
defmodule VrokWeb.OperationController do
  use VrokWeb, :controller
  require Logger

  def index(conn, _params) do
    operations = Vrok.OperationRepo.all()

    render conn, "index.html", operations: operations
  end
end

apps/vrok_web/lib/vrok_web/controllers/page_controller.ex
defmodule VrokWeb.PageController do
  use VrokWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

apps/vrok_web/lib/vrok_web/controllers/scene_controller.ex
defmodule VrokWeb.SceneController do
  use VrokWeb, :controller
  require Logger

  def index(conn, params) do
    operation_id = String.to_integer(params["operation_id"])
    scenes = Vrok.SceneRepo.by_operation(operation_id)

    render conn, "index.html", scenes: scenes
  end

  def show(conn, %{"operation_id" => operation_id, "id" => scene_id}) do
    render conn, "show.html", %{operation_id: operation_id, scene_id: scene_id}
  end
end

apps/vrok_web/lib/vrok_web/controllers/session_controller.ex
defmodule VrokWeb.SessionController do
  use VrokWeb, :controller
  alias Vrok.Repo

  def new(conn, _) do
    render(conn, "new.html")
  end

  def create(conn, %{"session" => %{"username" => user, "password" => pass}}) do
    case Vrok.Auth.login_by_username_and_pass(conn, user, pass, repo: Repo) do
      {:ok, conn} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> redirect(to: page_path(conn, :index))

      {:error, _reason, conn} ->
        conn
        |> put_flash(:error, "Invalid username/password combination")
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    conn
    |> Vrok.Auth.logout()
    |> redirect(to: page_path(conn, :index))
  end
end

apps/vrok_web/lib/vrok_web/controllers/user_controller.ex
defmodule VrokWeb.UserController do
  use VrokWeb, :controller
  plug :authenticate_user when action in [:index, :show]

  alias Vrok.User
  alias Vrok.Repo

  def index(conn, _params) do
    users = Repo.all(User)
    render(conn, "index.html", users: users)
  end

  def show(conn, %{"id" => id}) do
    user = Repo.get(User, id)
    render(conn, "show.html", user: user)
  end

  def new(conn, _params) do
    changeset = User.changeset(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    changeset = User.registration_changeset(%User{}, user_params)

    case Repo.insert(changeset) do
      {:ok, user} ->
        conn
        |> Vrok.Auth.login(user)
        |> put_flash(:info, "#{user.name} created!")
        |> redirect(to: user_path(conn, :index))

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

apps/vrok_web/lib/vrok_web/controllers/viewer_controller.ex
defmodule VrokWeb.ViewerController do
  use VrokWeb, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

apps/vrok_web/lib/vrok_web/views/controls_view.ex
defmodule VrokWeb.ControlsView do
  use VrokWeb, :view
end

apps/vrok_web/lib/vrok_web/views/error_view.ex
defmodule VrokWeb.ErrorView do
  use VrokWeb, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

apps/vrok_web/lib/vrok_web/views/layout_view.ex
defmodule VrokWeb.LayoutView do
  use VrokWeb, :view
end

apps/vrok_web/lib/vrok_web/views/operation_view.ex
defmodule VrokWeb.OperationView do
  use VrokWeb, :view

  def nice_tags(tags), do: Enum.join(tags, ", ")
end

apps/vrok_web/lib/vrok_web/views/page_view.ex
defmodule VrokWeb.PageView do
  use VrokWeb, :view
end

apps/vrok_web/lib/vrok_web/views/scene_view.ex
defmodule VrokWeb.SceneView do
  use VrokWeb, :view
end

apps/vrok_web/lib/vrok_web/views/session_view.ex
defmodule VrokWeb.SessionView do 
  use VrokWeb, :view
end

apps/vrok_web/lib/vrok_web/views/user_view.ex
defmodule VrokWeb.UserView do
  use VrokWeb, :view
  alias Vrok.User

  def first_name(%User{name: name}) do
    name
    |> String.split(" ")
    |> Enum.at(0)
  end
end

apps/vrok_web/lib/vrok_web/views/viewer_view.ex
defmodule VrokWeb.ViewerView do
  use VrokWeb, :view
end

apps/vrok_web/lib/vrok_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello VROK</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <script>window.userToken = "<%= assigns[:user_token] %>"</script>
    <script>window.userId = "<%= assigns[:user_id] %>"</script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <main role="main">
      <%= render @view_module, @view_template, assigns %>
    </main>
  </body>
</html>

apps/vrok_web/lib/vrok_web/templates/operation/index.html.eex
<div class="page operations">
  <div class="cSearchContainer"></div>
  <h1>Operaties</h1>
  <ul>
    <%= for operation <- @operations do %>
      <li><a href="/operations/<%= operation.id %>/scenes">
        <div class="title"><%= operation.title %></div>
        <div class="description"><%= operation.description %></div>
        <div class="tags"><%= nice_tags(operation.tags) %></div>
      </a></li>
    <% end %>
  </ul>
</div>
<script src="<%= static_path(@conn, "/js/controls.js") %>"></script>

apps/vrok_web/lib/vrok_web/templates/page/index.html.eex
  <div class="container">
    <div class="page home">
      <div class="logo"></div>
      <div class="tagline">Virtual Reality Operating Room</div>
      <ul class="menu"> 
        <%= if @current_user do %>
          <li><%= link "Browse operations", to: operation_path(@conn, :index) %></li>
          <li><%= link "Open Viewer", to: "/viewer" %></li>
        <% else %>
          <li><%= link "Register", to: session_path(@conn, :new) %></li>
          <li><%= link "Log in", to: session_path(@conn, :new) %></li>
        <% end %> 
      </ul>
    </div>
  </div--> <!-- /container -->

apps/vrok_web/lib/vrok_web/templates/scene/index.html.eex
<div class="page scenes">
  <h1>Scenes</h1>
  <ul>
    <%= for scene <- @scenes do %>
      <li><a href="/operations/<%= scene.operation_id %>/scenes/<%= scene.id %>"><%= scene.title %></a></li>
    <% end %>
  </ul>
</div>

apps/vrok_web/lib/vrok_web/templates/scene/show.html.eex
<div class="cControls">
</div>

<script>
  window.operationId = <%= @operation_id %>
  window.sceneId = <%= @scene_id %>
</script>
<script src="<%= static_path(@conn, "/js/controls.js") %>"></script>

apps/vrok_web/lib/vrok_web/templates/session/new.html.eex
<div class="page login">
  <h1>Login</h1>
  <%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %> 
    <div class="form-group">
      <%= text_input f, :username, placeholder: "Username", class: "form-control" %> </div>
    <div class="form-group">
      <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
    </div>
    <%= submit "Log in", class: "btn btn-primary" %> 
  <% end %>
</div>

apps/vrok_web/lib/vrok_web/templates/user/index.html.eex
<h1>Listing Users</h1>
<table class="table">
  <%= for user <- @users do %>
  <tr>
    <td><%= render "user.html", user: user %></td>
    <td><%= link "View", to: user_path(@conn, :show, user.id) %></td>
  </tr>
  <% end %> 
</table>

apps/vrok_web/lib/vrok_web/templates/user/new.html.eex
<h1>New User</h1>

<%= if @changeset.action do %> 
  <div class="alert alert-danger">
    <p>Oops, something went wrong! Please check the errors below.</p>
  </div>
<% end %>

<%= form_for @changeset, user_path(@conn, :create), fn f -> %> 
  <div class="form-group">
    <%= text_input f, :name, placeholder: "Name", class: "form-control" %> 
    <%= error_tag f, :name %>
  </div>
  <div class="form-group">
    <%= text_input f, :username, placeholder: "Username", class: "form-control" %>
    <%= error_tag f, :username %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password", class: "form-control" %> 
    <%= error_tag f, :password %>
  </div>
  <%= submit "Create User", class: "btn btn-primary" %> 
<% end %>

apps/vrok_web/lib/vrok_web/templates/user/show.html.eex
<h1>Showing User</h1>
<%= render "user.html", user: @user %>

apps/vrok_web/lib/vrok_web/templates/user/user.html.eex
<b><%= first_name(@user) %></b> (<%= @user.id %>)

apps/vrok_web/lib/vrok_web/templates/viewer/index.html.eex
<div class="cViewerWrapper"></div>
<script src="<%= static_path(@conn, "/js/viewer.js") %>"></script>